
BOOST_LIB = /Users/reinhardheckel/include/boost_1_55_0/stage/lib

testRS: testRS.cpp
	g++ -O3 testRS.cpp -o testRS -std=c++11 -lboost_program_options -L$(BOOST_LIB)

testShortRS: testShortRS.cpp
	g++ -O3 testShortRS.cpp -o testShortRS -std=c++11 -lboost_program_options -L$(BOOST_LIB)

test_EFE: test_EFE.cpp
	g++ -O3 test_EFE.cpp -o test_EFE -std=c++11 -lboost_program_options -L$(BOOST_LIB)


testEFEGF2: testEFEGF2.cpp
	g++ -O3 testEFEGF2.cpp -o testEFEGF2 -std=c++11 -lboost_program_options -L$(BOOST_LIB)


test_helpers: test_helpers.cpp
	g++ -O3 test_helpers.cpp -o test_helpers -std=c++11 -lboost_program_options -L$(BOOST_LIB)


